services:
  - type: web
    name: ump-cferi-web
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm run build
    postBuildCommand: cd backend && node create-admin.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        scope: build
      - key: PORT
        value: "5000"
